# Generated by Django 4.1.3 on 2022-11-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttn', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('sent_date', models.DateTimeField()),
                ('schedule_date', models.DateTimeField()),
                ('delivered_date', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_city', models.CharField(max_length=255)),
                ('recipient_name', models.CharField(max_length=255)),
                ('afterpayment_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
