# Generated by Django 4.1.3 on 2022-11-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='delivered_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='schedule_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='sent_date',
            field=models.DateField(),
        ),
    ]
