# Generated by Django 4.1.3 on 2022-11-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np', '0004_tracking_phone_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='afterpayment_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
