# Generated by Django 4.1.3 on 2022-11-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('np', '0005_alter_tracking_afterpayment_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='phone_recipient',
            field=models.CharField(default=380960042412, max_length=20),
            preserve_default=False,
        ),
    ]
