# Generated by Django 4.1.3 on 2022-11-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('np', '0007_alter_tracking_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='updated_at',
        ),
    ]
